package go_mhda

import (
	"crypto/sha1"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

type MHDA interface {
	Chain() *Chain
	DerivationType() DerivationType
	DerivationPath() *DerivationPath
	Algorithm() Algorithm
	Format() Format
	// WalletType returns the optional wallet-domain type ("wt"), e.g. "web3",
	// "metamask", "tonconnect". Empty when unset.
	WalletType() string
	// WalletId returns the optional wallet-domain instance id ("wi"), e.g. a
	// UUID or an HD root key fingerprint. Empty when unset.
	WalletId() string
	NSS() string
	String() string
	// Hash returns a SHA-1 digest of String(). Kept only so identifiers
	// generated by this version stay stable; SHA-1 is no longer
	// collision-resistant. Prefer Hash256.
	Hash() string
	// NSSHash returns a SHA-1 digest of NSS(). Same caveat as Hash.
	NSSHash() string
	// Hash256 returns the SHA-256 digest of String(), hex-encoded.
	Hash256() string
	// NSSHash256 returns the SHA-256 digest of NSS(), hex-encoded.
	NSSHash256() string
}

type Address struct {
	chain            *Chain
	path             *DerivationPath
	addressAlgorithm Algorithm
	addressFormat    Format
	addressPrefix    string
	addressSuffix    string
	walletType       string
	walletId         string
}

// NewAddress builds an Address from chain and derivation path. Optional params,
// in order, are: addressAlgorithm (aa), addressFormat (af), addressPrefix (ap),
// addressSuffix (as). Empty strings are treated as unset. The wallet domain
// (wt/wi) is set via SetWalletType / SetWalletId.
//
// Params are routed through the corresponding setters, so they are validated
// exactly like parsed input; an invalid value panics (programmer error at a
// construction site — mirroring the NewDerivationPath precedent). The parse
// entry points never panic.
//
// The address keeps its own copies of chain and path: changing them later,
// or another address built from them, does not change this one.
func NewAddress(chain *Chain, path *DerivationPath, params ...string) *Address {
	a := &Address{chain: chain.clone(), path: path.clone()}
	get := func(i int) string {
		if i < len(params) {
			return params[i]
		}
		return ""
	}
	set := func(f func(string) error, v string) {
		if err := f(v); err != nil {
			panic(err)
		}
	}
	set(a.SetAddressAlgorithm, get(0))
	set(a.SetAddressFormat, get(1))
	set(a.SetAddressPrefix, get(2))
	set(a.SetAddressSuffix, get(3))
	return a
}

func parseAddress(m map[string]string) (MHDA, error) {
	chain, err := parseChain(m)
	if err != nil {
		return nil, err
	}

	mhda := &Address{chain: chain}

	if err := mhda.SetDerivation(m[compDerivationType], m[compDerivationPath]); err != nil {
		return nil, err
	}
	if err := mhda.SetAddressAlgorithm(m[compAddressAlgorithm]); err != nil {
		return nil, err
	}
	if err := mhda.SetAddressFormat(m[compAddressFormat]); err != nil {
		return nil, err
	}
	if err := mhda.SetAddressPrefix(m[compAddressPrefix]); err != nil {
		return nil, err
	}
	if err := mhda.SetAddressSuffix(m[compAddressSuffix]); err != nil {
		return nil, err
	}
	if err := mhda.SetWalletType(m[compWalletType]); err != nil {
		return nil, err
	}
	if err := mhda.SetWalletId(m[compWalletId]); err != nil {
		return nil, err
	}
	return mhda, nil
}

func (a *Address) Chain() *Chain {
	return a.chain
}

// DerivationType returns the derivation type of the address' path, or ROOT
// if the address has no path.
func (a *Address) DerivationType() DerivationType {
	if a.path == nil {
		return ROOT
	}
	return a.path.derivationType
}

func (a *Address) DerivationPath() *DerivationPath {
	return a.path
}

// Algorithm returns the explicitly set algorithm or, if none was set, the
// default for the address' network type (see compatibility.go).
func (a *Address) Algorithm() Algorithm {
	if a.addressAlgorithm != "" {
		return a.addressAlgorithm
	}
	return defaultAlgorithm(a.chain.networkType)
}

// Format returns the explicitly set address format or, if none was set, the
// default for the address' network type. Networks with multiple legitimate
// formats (e.g. Bitcoin) return "" when nothing was set explicitly.
func (a *Address) Format() Format {
	if a.addressFormat != "" {
		return a.addressFormat
	}
	return defaultFormat(a.chain.networkType)
}

// SetDerivationType sets the derivation type; an empty string means ROOT.
// A type other than the current one drops the current path, which belongs to
// the old scheme: until SetDerivationPath sets a new one the address has no
// path, its URN carries dt without dp, and Validate / MarshalText refuse it.
// Setting the current type again keeps the path. Use SetDerivation to change
// both at once.
func (a *Address) SetDerivationType(dt string) error {
	dt = strings.TrimSpace(dt)
	dt = strings.ToLower(dt)

	next := ROOT
	if dt != `` {
		if _, ok := derivationIndex[DerivationType(dt)]; !ok {
			return fmt.Errorf("%w: %q", ErrInvalidDerivationType, dt)
		}
		next = DerivationType(dt)
	}

	if a.path == nil || a.path.derivationType != next {
		a.path = &DerivationPath{derivationType: next}
	}
	return nil
}

// SetDerivation sets the derivation type and path together, as a parsed URN
// does: both are validated first, and the address changes only if both are
// valid. An empty dt means ROOT, which takes an empty dp.
func (a *Address) SetDerivation(dt, dp string) error {
	var scratch Address
	if err := scratch.SetDerivationType(dt); err != nil {
		return err
	}
	if err := scratch.SetDerivationPath(dp); err != nil {
		return err
	}
	a.path = scratch.path
	return nil
}

// SetDerivationPath parses dp under the address' derivation type. A root
// address has no path: an empty dp is accepted, anything else is refused
// with ErrInvalidDerivationPath. Dropping it instead would let a URN with a
// dp but no dt (which parses as root) name the root key rather than the
// path it spells out.
func (a *Address) SetDerivationPath(dp string) error {
	if a.path.derivationType == ROOT {
		if p := strings.TrimSpace(dp); p != `` {
			return fmt.Errorf("%w: root derivation must have empty path, got %q", ErrInvalidDerivationPath, p)
		}
		return nil
	}

	rx, ok := derivationIndex[a.path.derivationType]
	if !ok {
		return fmt.Errorf("%w: unknown derivation type %q", ErrInvalidDerivationPath, a.path.derivationType)
	}

	dp = strings.TrimSpace(dp)
	dp = strings.ToLower(dp)

	if !rx.MatchString(dp) {
		return fmt.Errorf("%w: %q", ErrInvalidDerivationPath, dp)
	}

	// ParsePath wraps its own errors with the appropriate sentinel; surface
	// the result unchanged so callers can errors.Is(...) the inner sentinel.
	return a.path.ParsePath(dp)
}

// SetCoinType sets the optional SLIP-44 coin-type metadata on the address'
// chain. Passing an empty string clears it. Accepted spellings are plain
// decimal and 0x-prefixed hex (see parseCoinType).
func (a *Address) SetCoinType(ct string) error {
	ct = strings.TrimSpace(ct)
	if ct == `` {
		a.chain.ClearCoinType()
		return nil
	}

	coinType, err := parseCoinType(ct)
	if err != nil {
		return err
	}

	a.chain.SetCoinType(coinType)
	return nil
}

// validateFreeFormValue guards the case-preserving free-form components
// (ap/as/wt/wi) against characters that would corrupt the serialised NSS:
// the ':' component separator would inject foreign components on re-parse,
// '?' / '#' would truncate the URN at the RFC 8141 r/q/f delimiters, and
// anything outside printable ASCII (whitespace of any kind, control bytes,
// Unicode) cannot appear in a conforming NSS at all.
func validateFreeFormValue(component, v string) error {
	for i := 0; i < len(v); i++ {
		if v[i] < 0x21 || v[i] > 0x7e || v[i] == ':' || v[i] == '?' || v[i] == '#' {
			return fmt.Errorf("%w: %q for %q", ErrInvalidValue, v, component)
		}
	}
	return nil
}

func (a *Address) SetAddressAlgorithm(aa string) error {
	aa = strings.TrimSpace(aa)
	aa = strings.ToLower(aa)
	if aa == `` {
		a.addressAlgorithm = ""
		return nil
	}
	if _, ok := indexAlgorithms[Algorithm(aa)]; !ok {
		return fmt.Errorf("%w: %q", ErrInvalidAlgorithm, aa)
	}
	a.addressAlgorithm = Algorithm(aa)
	return nil
}

func (a *Address) SetAddressFormat(af string) error {
	af = strings.TrimSpace(af)
	af = strings.ToLower(af)
	if af == `` {
		a.addressFormat = ""
		return nil
	}
	if _, ok := indexFormats[Format(af)]; !ok {
		return fmt.Errorf("%w: %q", ErrInvalidFormat, af)
	}
	a.addressFormat = Format(af)
	return nil
}

// SetAddressPrefix sets the optional address prefix. Passing an empty string
// resets the prefix - matching the semantics of SetAddressAlgorithm and
// SetAddressFormat. Values are validated against NSS-corrupting characters
// (see validateFreeFormValue).
func (a *Address) SetAddressPrefix(ap string) error {
	ap = asciiTrim(ap)
	if err := validateFreeFormValue(compAddressPrefix, ap); err != nil {
		return err
	}
	a.addressPrefix = ap
	return nil
}

// SetAddressSuffix sets the optional address suffix. Passing an empty string
// resets the suffix. Values are validated against NSS-corrupting characters.
func (a *Address) SetAddressSuffix(as string) error {
	as = asciiTrim(as)
	if err := validateFreeFormValue(compAddressSuffix, as); err != nil {
		return err
	}
	a.addressSuffix = as
	return nil
}

// SetWalletType sets the optional wallet-domain type ("wt"), a free-form
// string such as "web3", "metamask" or "tonconnect". Passing an empty string
// resets it. Values are validated against NSS-corrupting characters — the
// wallet domain carries client-supplied identifiers, so an embedded ':'
// must never be able to inject foreign components into the URN.
func (a *Address) SetWalletType(wt string) error {
	wt = asciiTrim(wt)
	if err := validateFreeFormValue(compWalletType, wt); err != nil {
		return err
	}
	a.walletType = wt
	return nil
}

// SetWalletId sets the optional wallet-domain instance id ("wi"), a free-form
// string such as a UUID or an HD root key fingerprint. Passing an empty
// string resets it. Values are validated against NSS-corrupting characters.
func (a *Address) SetWalletId(wi string) error {
	wi = asciiTrim(wi)
	if err := validateFreeFormValue(compWalletId, wi); err != nil {
		return err
	}
	a.walletId = wi
	return nil
}

// WalletType returns the optional wallet-domain type, or "" when unset.
func (a *Address) WalletType() string { return a.walletType }

// WalletId returns the optional wallet-domain instance id, or "" when unset.
func (a *Address) WalletId() string { return a.walletId }

func (a *Address) String() string {
	return fmt.Sprintf(`urn:mhda:%s`, a.NSS())
}

// NSS returns the URN namespace-specific string in canonical form. The
// emission order is the chain identity (nt/ci) first — so the chain key is a
// strict prefix of the NSS — then the optional coin-type metadata (ct), the
// derivation domain (dt/dp), address-format metadata (aa/af/ap/as), and the
// wallet domain (wt/wi) last. Optional components are emitted only when
// explicitly set, preserving the round-trip with short input forms.
func (a *Address) NSS() string {
	var b strings.Builder

	// Chain identity - always present.
	_, _ = fmt.Fprintf(&b, "nt:%s:ci:%s", a.chain.networkType, a.chain.chainId)

	// Coin-type metadata - emitted only when explicitly set.
	if a.chain.hasCoinType {
		_, _ = fmt.Fprintf(&b, ":ct:%d", a.chain.coinType)
	}

	// Derivation domain - present when a type other than ROOT is set. A type
	// set without a path yet is emitted without dp, so the URN fails to parse
	// rather than name another key.
	if a.path != nil && a.path.derivationType != ROOT && a.path.derivationType != "" {
		b.WriteString(":dt:")
		b.WriteString(string(a.path.derivationType))
		if p := a.path.String(); p != "" {
			b.WriteString(":dp:")
			b.WriteString(p)
		}
	}

	// Address-format metadata - emitted only when explicitly set.
	if a.addressAlgorithm != "" {
		b.WriteString(":aa:")
		b.WriteString(string(a.addressAlgorithm))
	}
	if a.addressFormat != "" {
		b.WriteString(":af:")
		b.WriteString(string(a.addressFormat))
	}
	if a.addressPrefix != "" {
		b.WriteString(":ap:")
		b.WriteString(a.addressPrefix)
	}
	if a.addressSuffix != "" {
		b.WriteString(":as:")
		b.WriteString(a.addressSuffix)
	}

	// Wallet domain - emitted only when explicitly set.
	if a.walletType != "" {
		b.WriteString(":wt:")
		b.WriteString(a.walletType)
	}
	if a.walletId != "" {
		b.WriteString(":wi:")
		b.WriteString(a.walletId)
	}

	return b.String()
}

// Hash returns a SHA-1 digest of String() as hex. Kept only so identifiers
// generated by this version stay stable; SHA-1 is broken under collision
// attacks and should not be relied upon for new uses. Prefer Hash256.
func (a *Address) Hash() string {
	h := sha1.New()
	h.Write([]byte(a.String()))
	return hex.EncodeToString(h.Sum(nil))
}

// NSSHash returns a SHA-1 digest of NSS() as hex. Same caveat as Hash.
func (a *Address) NSSHash() string {
	h := sha1.New()
	h.Write([]byte(a.NSS()))
	return hex.EncodeToString(h.Sum(nil))
}

// Hash256 returns a SHA-256 digest of String() as hex. Use this for content-
// addressing or deduplication keys.
func (a *Address) Hash256() string {
	sum := sha256.Sum256([]byte(a.String()))
	return hex.EncodeToString(sum[:])
}

// NSSHash256 returns a SHA-256 digest of NSS() as hex.
func (a *Address) NSSHash256() string {
	sum := sha256.Sum256([]byte(a.NSS()))
	return hex.EncodeToString(sum[:])
}

// MarshalText implements encoding.TextMarshaler. This is the integration point
// for encoding/json, encoding/xml, gopkg.in/yaml.v3 and similar codecs - they
// will produce the URN form automatically.
func (a *Address) MarshalText() ([]byte, error) {
	if a == nil || a.chain == nil {
		return nil, ErrUninitializedAddress
	}
	if err := a.checkPathSet(); err != nil {
		return nil, err
	}
	return []byte(a.String()), nil
}

// checkPathSet reports a derivation type set without a path (see
// SetDerivationType): such an address serialises to a URN that does not parse.
func (a *Address) checkPathSet() error {
	if a.path != nil && a.path.derivationType != ROOT && a.path.derivationType != "" && len(a.path.levels) == 0 {
		return fmt.Errorf("%w: derivation type %q is set without a path", ErrInvalidDerivationPath, a.path.derivationType)
	}
	return nil
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (a *Address) UnmarshalText(data []byte) error {
	parsed, err := ParseURN(string(data))
	if err != nil {
		return err
	}
	p, ok := parsed.(*Address)
	if !ok {
		return ErrInvalidURN
	}
	*a = *p
	return nil
}
